// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecond;

import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.RobotState;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.Constants.FieldConstants;
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.TripleShooterSubsystem;
import frc.robot.utils.AllianceUtil;
import frc.robot.utils.LaunchCalculator;
import frc.robot.utils.ShootingData;
import frc.robot.utils.geometry.AllianceFlipUtil;

/**
 * This routine is enabled by holding a gamepad trigger/ bumper while using the
 * gamepad left stick to drive the robot.
 * Its purpose is to align the shooter with the hub directly if the robot is
 * stationary or with the drive angle generated by the LaunchCalculator if the
 * robot is moving.
 * 
 * 
 * 
 * 
 */

public class DriveWithShootOnTheMove extends Command {
  /** Creates a new AlignToTagSet */
  CommandXboxController m_controller;
  // Slew rate limiters to make joystick inputs more gentle; 1/3 sec from 0 to 1.
  private SlewRateLimiter translationLimiter = new SlewRateLimiter(3.0);
  private SlewRateLimiter strafeLimiter = new SlewRateLimiter(3.0);
  private SlewRateLimiter rotationLimiter = new SlewRateLimiter(3.0);

  private final CommandSwerveDrivetrain m_drivetrain;
  private double kp = .05;
  private double ki = .0;
  private double kd = .0;

  public PIDController m_alignTargetPID = new PIDController(kp, ki, kd);
  private double rotationVal;
  private double angleError;
  private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
  private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond);

  private SwerveRequest.FieldCentric drive;
  private final TripleShooterSubsystem shooter;
  private Pose2d targetPose;
  private double deadband = .02;
  private double distanceToHub;
  private double shooterRPM;
  private double hoodAngle;

  public DriveWithShootOnTheMove(
      CommandSwerveDrivetrain drivetrain,
      TripleShooterSubsystem shooter,
      SwerveRequest.FieldCentric drive,
      CommandXboxController controller) {

    m_drivetrain = drivetrain;
    m_controller = controller;
    this.drive = drive;
    this.shooter = shooter;
    addRequirements(m_drivetrain);
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {
    m_alignTargetPID.enableContinuousInput(-180, 180);
    // if (!lob) {
    targetPose = AllianceUtil.getHubPose();
    m_alignTargetPID.setTolerance(0.2);
  }

  // Called every time the scheduler runs while the command is scheduled.
  @Override
  public void execute() {

  
  
  LaunchCalculator.LaunchingParameters lp = LaunchCalculator.getInstance().getParameters(m_drivetrain);
    SmartDashboard.putBoolean("LC/lp", false);
    if (lp != null) {
      SmartDashboard.putBoolean("LC/lp", true);

     
    boolean passing = lp.passing();

    distanceToHub = lp.distance()

    shooterRPM = lp.flywheelSpeed();

    hoodAngle = lp.hoodAngle();

      SmartDashboard.putNumber("LC/pomtsa", m_drivetrain.projectedOnTheMoveShootAngle.getDegrees());
      angleError = m_drivetrain.getState().Pose.getRotation().minus(lp.driveAngle()).getDegrees();

      rotationVal = lp.driveVelocity()
          + lp.driveAngle()
              .minus(m_drivetrain.getState().Pose.getRotation())
              .getRadians() * kp

          + (lp.driveVelocity()
              - m_drivetrain.getState().Speeds.omegaRadiansPerSecond) * kd;

      rotationVal = m_alignTargetPID.calculate(lp.driveVelocity() + angleError, 0);

      double gamePadRotate = m_controller.getRightX();

      if (Math.abs(gamePadRotate) < deadband)
        gamePadRotate = 0;

      m_drivetrain.setControl(
          drive.withVelocityX(-m_controller.getLeftY() * MaxSpeed)
              .withVelocityY(-m_controller.getLeftX() * MaxSpeed)
              // // negative X (left)
              .withRotationalRate(gamePadRotate + rotationVal * MaxAngularRate));

      SmartDashboard.putNumber("LC/Rotval", rotationVal);

      SmartDashboard.putNumber("LC/AngleError", angleError);

      m_drivetrain.alignedToTarget = Math.abs(angleError) < m_drivetrain.shootTolerance;

      SmartDashboard.putBoolean("LC/AlignedToAngle", m_drivetrain.alignedToTarget);

      LaunchCalculator.getInstance().clearLaunchingParameters();
    }

  }

  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {
  }

  // Returns true when the command should end.
  @Override
  public boolean isFinished() {
    return false;
  }

  public double getAngleDegreesToTarget(Pose2d targetPose, Pose2d robotPose) {
    double XDiff = targetPose.getX() - robotPose.getX();
    double YDiff = targetPose.getY() - robotPose.getY();
    return Units.radiansToDegrees(Math.atan2(YDiff, XDiff));
  }
}
