// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import static edu.wpi.first.units.Units.Meters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.Seconds;

import java.util.function.Supplier;

import com.ctre.phoenix6.swerve.SwerveRequest;

import dev.doglog.DogLog;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.Time;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.Constants.FieldConstants;
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.HoodSubsystem;
import frc.robot.subsystems.TripleShooterSubsystem;
import frc.robot.utils.AllianceUtil;
import frc.robot.utils.ShootingData;
import frc.robot.utils.geometry.AllianceFlipUtil;

/**
 * This routine is enabled by holding a gamepad trigger/ bumper while using the
 * gamepad left stick to drive the robot.
 * Its purpose is to align the shooter with the hub directly if the robot is
 * stationary or with the drive angle generated by the LaunchCalculator if the
 * robot is moving.
 * 
 * 
 * 
 * 
 */

public class DriveWithShootOnTheMove extends Command {
  /** Creates a new AlignToTagSet */
  CommandXboxController m_controller;
  // Slew rate limiters to make joystick inputs more gentle; 1/3 sec from 0 to 1.
  private SlewRateLimiter translationLimiter = new SlewRateLimiter(3.0);
  private SlewRateLimiter strafeLimiter = new SlewRateLimiter(3.0);
  private SlewRateLimiter rotationLimiter = new SlewRateLimiter(3.0);

  private final CommandSwerveDrivetrain m_swerve;
  private final HoodSubsystem m_hood;
  private double kp = .0025;
  private double ki = .0;
  private double kd = .0;

  public PIDController m_alignTargetPID = new PIDController(kp, ki, kd);
  private double rotationVal;
  private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
  private double MaxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond);

  private SwerveRequest.FieldCentric drive;
  private final TripleShooterSubsystem shooter;
  private Pose2d targetPose;
  private boolean passing;
  private static Distance distance;
  private static Distance newDistance;
  private static Time timeOfFlight;

  public DriveWithShootOnTheMove(
      CommandSwerveDrivetrain swerve,
      HoodSubsystem hood,
      TripleShooterSubsystem shooter,
      SwerveRequest.FieldCentric drive,
      CommandXboxController controller) {

    m_swerve = swerve;
    m_hood = hood;
    m_controller = controller;
    this.drive = drive;
    this.shooter = shooter;
    addRequirements(m_swerve);
  }

  // Called when the command is initially scheduled.
  @Override
  public void initialize() {
    m_alignTargetPID.enableContinuousInput(-180, 180);
    // if (!lob) {
    targetPose = AllianceUtil.getHubPose();
    m_alignTargetPID.setTolerance(0.2);
    m_swerve.isAligning = true;
    shooter.isShootOnTheMove = true;
  }

  // Called every time the scheduler runs while the command is scheduled.
  @Override
  public void execute() {

    Pose2d robotPose = m_swerve.getState().Pose;

    passing = AllianceFlipUtil
        .applyX(robotPose.getX()) > FieldConstants.LinesVertical.hubCenter;
    if (!passing) {
      targetPose = AllianceUtil.getHubPose();
    } else
      targetPose = AllianceUtil.getPassingTargetPose(robotPose);

    Translation2d aimPoint = calculateLeadTarget(m_swerve, () -> targetPose.getTranslation());

    double distanceToTarget = newDistance.in(Meters);

    shooter.setAutoSetTargetRPM(passing ? ShootingData.passingShooterSpeedMap.get(distanceToTarget)
        : ShootingData.shooterSpeedMap.get(distanceToTarget));

    m_hood.setAutoTargetAngle(passing ? ShootingData.passingHoodAngleMap.get(distanceToTarget).getDegrees()
        : ShootingData.hoodAngleMap.get(distanceToTarget).getDegrees());

    distanceToTarget = targetPose.getTranslation()
        .getDistance(robotPose.getTranslation());

    shooter.setAutoSetTargetRPM(passing ? ShootingData.passingShooterSpeedMap.get(distanceToTarget)
        : ShootingData.shooterSpeedMap.get(distanceToTarget));

    Pose2d aimPose = new Pose2d(aimPoint, new Rotation2d(Math.PI));

    double targetDegrees = getAngleDegreesToTarget(aimPose, robotPose);

    if (Math.abs(m_swerve.m_alignTargetPID.getError()) > m_swerve.alignIzone) {
      m_swerve.m_alignTargetPID.setIntegratorRange(0, 0);
    } else
      m_swerve.m_alignTargetPID.setIntegratorRange(-.1, .1);

    rotationVal = m_swerve.m_alignTargetPID.calculate(m_swerve.getState().Pose.getRotation().getDegrees(),
        targetDegrees);

    m_swerve.setControl(
        drive.withVelocityX(-m_controller.getLeftY() * MaxSpeed)
            .withVelocityY(-m_controller.getLeftX() * MaxSpeed)
            // // negative X (left)
            .withRotationalRate(rotationVal * MaxAngularRate));

    m_swerve.alignedToTarget = Math.abs(m_alignTargetPID.getError()) < m_swerve.shootTolerance;

    DogLog.log("SOTM/RobotPose", robotPose);
    DogLog.log("SOTM/TargetPose", targetPose);
    DogLog.log("SOTM/AimPose", aimPose);
    DogLog.log("SOTM/Passing", passing);
    DogLog.log("SOTM/AimPos", aimPoint);
    DogLog.log("SOTM/Distance", distanceToTarget);
    DogLog.log("SOTM/DegreesToTarget", targetDegrees);
    DogLog.log("SOTM/RotnVal", rotationVal);
    DogLog.log("SOTM/RotnError", m_alignTargetPID.getError());    
    DogLog.log("SOTM/AlignedToHub", m_swerve.alignedToTarget);

  }

  // Called once the command ends or is interrupted.
  @Override
  public void end(boolean interrupted) {
    shooter.isShootOnTheMove = false;
    m_swerve.isAligning = false;
  }

  // Returns true when the command should end.
  @Override
  public boolean isFinished() {
    return false;
  }

  public double getAngleDegreesToTarget(Pose2d targetPose, Pose2d robotPose) {
    double XDiff = targetPose.getX() - robotPose.getX();
    double YDiff = targetPose.getY() - robotPose.getY();
    return Units.radiansToDegrees(Math.atan2(YDiff, XDiff));
  }

  private static Translation2d calculateLeadTarget(CommandSwerveDrivetrain drive, Supplier<Translation2d> target) {
    Translation2d robotPos = drive.getState().Pose.getTranslation();
    Translation2d targetPos = target.get();

    ChassisSpeeds fieldSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(drive.getState().Speeds,
        drive.getState().Pose.getRotation());
    Translation2d velocityVec = new Translation2d(fieldSpeeds.vxMetersPerSecond, fieldSpeeds.vyMetersPerSecond);

    distance = Meters.of(targetPos.getDistance(drive.getState().Pose.getTranslation()));

    timeOfFlight = Seconds.of(ShootingData.timeOfFlightMap.get(distance.in(Meters)));

    Translation2d aimPoint = new Translation2d();

    for (int i = 0; i < 20; i++) {

      Translation2d motionOffset = velocityVec.times(timeOfFlight.in(Seconds));

      aimPoint = targetPos.minus(motionOffset);

      newDistance = Meters.of(aimPoint.getDistance(robotPos));

      timeOfFlight = Seconds.of(ShootingData.timeOfFlightMap.get(newDistance.in(Meters)));

     
    }
    return aimPoint;
  }

}
