// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.utils;

import static edu.wpi.first.units.Units.Meters;

import java.nio.channels.ShutdownChannelGroupException;

import dev.doglog.DogLog;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.interpolation.InterpolatingTreeMap;
import edu.wpi.first.math.interpolation.InverseInterpolator;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Constants;
import frc.robot.Constants.FieldConstants;
import frc.robot.Constants.LauncherConstants;
import frc.robot.Constants.RobotConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.subsystems.TripleShooterSubsystem;
import frc.robot.utils.geometry.AllianceFlipUtil;
import frc.robot.utils.geometry.GeomUtil;

/**
 * Read the estimated robot pose and shift it forward by a fixed (small) amount
 * using a Twist2d. We know that subsystems will not perfectly track the
 * setpoints, so this step helps to account for that phase delay by
 * calculating using a future robot position. We manually measure the phase
 * delay in subsystem tracking, and want to minimize it as much as possible to
 * improve the consistency under acceleration.
 * 
 * Calculate the position and velocity of the shooter. While we can
 * measure distance from anywhere on the robot with a fixed launcher, it’s very
 * important to measure from the shooter itself since we can launch in any
 * orientation. The same thing applies to velocity calculations, since the robot
 * and shooter velocities may be different (particularly when the robot is
 * turning).
 * 
 * Account for the velocity applied to the fuel by the robot (code). This is the
 * core of the algorithm, and involves three steps:
 * 
 * Calculate the expected time-of-flight of the ball using a lookup table
 * generated by sampling the time at several distances using a slo-mo video.
 * 
 * Shift the launcher position forward by the time-of-flight. We use a simple
 * transform and not a twist because we are not predicting the movement of the
 * robot; we are accounting for the offset of the ball over the course of its
 * flight.
 * 
 * Calculate the time-of-flight at the new lookahead position, and repeat the
 * calculation several times. This ensures that the time-of-flight used during
 * calculation matches the time-of-flight of the lookahead position.
 * 
 * Calculate the launch parameters using the lookahead position (code). This
 * step also calculates the derivative of the turret and hood setpoints, which
 * are fed to those subsystems to minimize phase delay during tracking.
 * 
 * 
 */
public class LaunchCalculator {

  public record LaunchingParameters(
      boolean isValid,
      Rotation2d driveAngle,
      double driveVelocity,
      double hoodAngle,
      double hoodVelocity,
      double flywheelSpeed,
      double distance,
      double distanceNoLookahead,
      double timeOfFlight,
      boolean passing) {
  }

  // Cache parameters
  private LaunchingParameters latestParameters = null;

  private static final double minDistance = .9;
  private static final double maxDistance = 4.9;
  private static final double passingMinDistance = 0;
  private static final double passingMaxDistance = 12;
  private static final double phaseDelay = .03;
  private final int loops = 20;

  private final CommandSwerveDrivetrain drivetrain;
  private final TripleShooterSubsystem shooter;

  private Rotation2d lastDriveAngle = new Rotation2d();

  private double lastHoodAngle;

  private double hoodAngleOffsetDeg = 0.0;

  public double getHoodAngleOffsetDeg() {
    return hoodAngleOffsetDeg;
  }

  private int loopTST;

  StructPublisher<Pose2d> robotPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/RobotPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> estimatedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/EstimatedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> lookAheadRobotPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LookAheadRobotPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> lookAheadPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LookAheadPose", Pose2d.struct).publish();

  StructPublisher<Pose2d> shooterPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LauncherPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> stAimedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/StAimedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> derivedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/DerivedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> projectedHubPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/ProjectedHubPose", Pose2d.struct).publish();

  boolean showData;

  public LaunchCalculator(CommandSwerveDrivetrain drivetrain, TripleShooterSubsystem shooter, boolean showData) {
    this.drivetrain = drivetrain;
    this.shooter = shooter;
    this.showData = showData;
  }

  // Launching Maps
  private static final InterpolatingTreeMap<Double, Rotation2d> hoodAngleMap = new InterpolatingTreeMap<>(
      InverseInterpolator.forDouble(), Rotation2d::interpolate);
  private static final InterpolatingDoubleTreeMap flywheelSpeedMap = new InterpolatingDoubleTreeMap();
  private static final InterpolatingDoubleTreeMap timeOfFlightMap = new InterpolatingDoubleTreeMap();

  // Passing Maps
  private static final InterpolatingTreeMap<Double, Rotation2d> passingHoodAngleMap = new InterpolatingTreeMap<>(
      InverseInterpolator.forDouble(), Rotation2d::interpolate);
  private static final InterpolatingDoubleTreeMap passingFlywheelSpeedMap = new InterpolatingDoubleTreeMap();
  private static final InterpolatingDoubleTreeMap passingTimeOfFlightMap = new InterpolatingDoubleTreeMap();
  // Passing targets
  private static final double hubPassLine = FieldConstants.LinesHorizontal.rightBumpStart
      - RobotConstants.trackWidthY / 2.0;
  private static final double xPassTarget = Units.inchesToMeters(25);
  private static final double yPassTarget = Units.inchesToMeters(50);

  static {

    hoodAngleMap.put(0.96, Rotation2d.fromDegrees(10.0));
    hoodAngleMap.put(1.16, Rotation2d.fromDegrees(12.0));
    hoodAngleMap.put(1.58, Rotation2d.fromDegrees(14.0));
    hoodAngleMap.put(2.07, Rotation2d.fromDegrees(18.5));
    hoodAngleMap.put(2.37, Rotation2d.fromDegrees(22.0));
    hoodAngleMap.put(2.47, Rotation2d.fromDegrees(23.0));
    hoodAngleMap.put(2.70, Rotation2d.fromDegrees(24.0));
    hoodAngleMap.put(2.94, Rotation2d.fromDegrees(25.0));
    hoodAngleMap.put(3.48, Rotation2d.fromDegrees(27.0));
    hoodAngleMap.put(3.92, Rotation2d.fromDegrees(32.0));
    hoodAngleMap.put(4.35, Rotation2d.fromDegrees(34.0));
    hoodAngleMap.put(4.84, Rotation2d.fromDegrees(38.0));

    flywheelSpeedMap.put(0.96, 150.0);
    flywheelSpeedMap.put(1.16, 155.0);
    flywheelSpeedMap.put(1.58, 160.0);
    flywheelSpeedMap.put(2.07, 165.0);
    flywheelSpeedMap.put(2.37, 170.0);
    flywheelSpeedMap.put(2.47, 170.0);
    flywheelSpeedMap.put(2.70, 170.0);
    flywheelSpeedMap.put(2.94, 175.0);
    flywheelSpeedMap.put(3.48, 175.0);
    flywheelSpeedMap.put(3.92, 180.0);
    flywheelSpeedMap.put(4.35, 185.0);
    flywheelSpeedMap.put(4.84, 190.0);

    timeOfFlightMap.put(5.68, 1.16);
    timeOfFlightMap.put(4.55, 1.12);
    timeOfFlightMap.put(3.15, 1.11);
    timeOfFlightMap.put(1.88, 1.09);
    timeOfFlightMap.put(1.38, 0.90);

    passingHoodAngleMap.put(5.46, Rotation2d.fromDegrees(38.0));
    passingHoodAngleMap.put(6.62, Rotation2d.fromDegrees(38.0));
    passingHoodAngleMap.put(7.80, Rotation2d.fromDegrees(38.0));

    passingFlywheelSpeedMap.put(5.46, 160.0);
    passingFlywheelSpeedMap.put(6.62, 180.0);
    passingFlywheelSpeedMap.put(7.80, 200.0);

    passingTimeOfFlightMap.put(passingMinDistance, 0.0);
    passingTimeOfFlightMap.put(passingMaxDistance, 0.0);

  }

  public static double getMinTimeOfFlight() {
    return timeOfFlightMap.get(minDistance);
  }

  public static double getMaxTimeOfFlight() {
    return timeOfFlightMap.get(maxDistance);
  }

  public LaunchingParameters getParameters() {
    boolean passing = AllianceFlipUtil
        .applyX(drivetrain.getState().Pose.getX()) > FieldConstants.LinesVertical.hubCenter;
    if (latestParameters != null) {
      return latestParameters;
    }

    /**
     * Read the estimated robot pose and shift it forward by a fixed (small) amount
     * using a Twist2d. We know that subsystems will not perfectly track the
     * setpoints, so this step helps to account for that phase delay by
     * calculating using a future robot position. We manually measure the phase
     * delay in subsystem tracking, and want to minimize it as much as possible to
     * improve the consistency under acceleration.
     */

    Pose2d robotPose = drivetrain.getState().Pose;
    ChassisSpeeds robotRelativeVelocity = drivetrain.getState().Speeds;
    Pose2d estimatedPose = robotPose.exp(
        new Twist2d(
            robotRelativeVelocity.vxMetersPerSecond * phaseDelay,
            robotRelativeVelocity.vyMetersPerSecond * phaseDelay,
            robotRelativeVelocity.omegaRadiansPerSecond * phaseDelay));

    if (showData) {
      robotPosePublisher.accept(robotPose);
      estimatedPosePublisher.accept(estimatedPose);
    }

    /**
     * Calculate the position and velocity of the shooter. While we can
     * measure distance from anywhere on the robot with a fixed launcher, it’s very
     * important to measure from the shooter itself since we can launch in any
     * orientation. The same thing applies to velocity calculations, since the robot
     * and shooter velocities may be different (particularly when the robot is
     * turning).
     */

    Translation2d target = passing
        ? getPassingTarget()
        : AllianceFlipUtil.apply(FieldConstants.Hub.topCenterPoint.toTranslation2d());

    Pose2d shooterPose = estimatedPose.transformBy(LauncherConstants.toTransform2d(LauncherConstants.robotToShooter));

    double shooterToTargetDistance = target.getDistance(shooterPose.getTranslation());

    if (showData) {
      shooterPosePublisher.accept(shooterPose);
      SmartDashboard.putNumber("LC/Lchr2TgtDist", shooterToTargetDistance);
    }
    /**
     * 
     * Account for the velocity applied to the fuel by the robot. This is the
     * core of the algorithm, and involves three steps:
     * 
     * Calculate the expected time-of-flight of the ball using a lookup table
     * generated by sampling the time at several distances using a slo-mo video.
     * 
     * Shift the launcher position forward by the time-of-flight. We use a simple
     * transform and not a twist because we are not predicting the movement of the
     * robot; we are accounting for the offset of the ball over the course of its
     * flight.
     * 
     * Calculate the time-of-flight at the new lookahead position, and repeat the
     * calculation several times. This ensures that the time-of-flight used during
     * calculation matches the time-of-flight of the lookahead position.
     * 
     */

    ChassisSpeeds shootererVelocity = GeomUtil.transformVelocity(
        drivetrain.getState().Speeds,
        LauncherConstants.robotToShooter.getTranslation().toTranslation2d(),
        drivetrain.getState().Pose.getRotation());

    // Account for imparted velocity by robot (shooter) to offset
    double timeOfFlight = passing
        ? passingTimeOfFlightMap.get(shooterToTargetDistance)
        : timeOfFlightMap.get(shooterToTargetDistance);
    Pose2d lookaheadPose = shooterPose;
    double lookaheadShooterToTargetDistance = shooterToTargetDistance;

    // loop to get better time of filght
    for (int i = 0; i < loops; i++) {
      timeOfFlight = passing
          ? passingTimeOfFlightMap.get(lookaheadShooterToTargetDistance)
          : timeOfFlightMap.get(lookaheadShooterToTargetDistance);
      double offsetX = shootererVelocity.vxMetersPerSecond * timeOfFlight;
      double offsetY = shootererVelocity.vyMetersPerSecond * timeOfFlight;
      lookaheadPose = new Pose2d(
          shooterPose.getTranslation().plus(new Translation2d(offsetX, offsetY)),
          shooterPose.getRotation());

      if (showData) {
        lookaheadShooterToTargetDistance = target.getDistance(lookaheadPose.getTranslation());
        lookAheadPosePublisher.accept(lookaheadPose);
      }
    }

    // Account for shoother being off center
    Pose2d lookaheadRobotPose = lookaheadPose
        .transformBy(LauncherConstants.toTransform2d(LauncherConstants.robotToShooter).inverse());
    Rotation2d driveAngle = getDriveAngleWithLauncherOffset(lookaheadRobotPose, target);

    LinearFilter hoodAngleFilter = LinearFilter.movingAverage((int) (0.4 / Constants.loopPeriodSecs));
    LinearFilter driveAngleFilter = LinearFilter.movingAverage((int) (1.5 / Constants.loopPeriodSecs));

    if (showData) {
      lookAheadRobotPosePublisher.accept(lookaheadRobotPose);
    }
    /**
     * 
     * Calculate the launch parameters using the lookahead position (code). This
     * step also calculates the derivative of the turret and hood setpoints, which
     * are fed to those subsystems to minimize phase delay during tracking.
     * 
     */
    double hoodAngle = passing
        ? passingHoodAngleMap.get(lookaheadShooterToTargetDistance).getRadians()
        : hoodAngleMap.get(lookaheadShooterToTargetDistance).getRadians();

    if (lastDriveAngle == null)
      lastDriveAngle = driveAngle;

    if (Double.isNaN(lastHoodAngle))
      lastHoodAngle = hoodAngle;

    double hoodVelocity = hoodAngleFilter.calculate((hoodAngle - lastHoodAngle) / Constants.loopPeriodSecs);
    lastHoodAngle = hoodAngle;

    double driveVelocity = driveAngleFilter.calculate(
        driveAngle.minus(lastDriveAngle).getRadians() / Constants.loopPeriodSecs);

    lastDriveAngle = driveAngle;

    if (showData) {
      SmartDashboard.putNumber("LC/LchrVelX", shootererVelocity.vxMetersPerSecond);
      SmartDashboard.putNumber("LC/LchrVelY", shootererVelocity.vyMetersPerSecond);
      SmartDashboard.putNumber("LC/LkAhdLchr2TgtDis", lookaheadShooterToTargetDistance);
    }

    // Construct parameters
    latestParameters = new LaunchingParameters(
        lookaheadShooterToTargetDistance >= (passing ? passingMinDistance : minDistance)
            && lookaheadShooterToTargetDistance <= (passing ? passingMaxDistance : maxDistance),
        driveAngle,
        driveVelocity,
        hoodAngle + Units.degreesToRadians(hoodAngleOffsetDeg),
        hoodVelocity,
        passing
            ? passingFlywheelSpeedMap.get(lookaheadShooterToTargetDistance)
            : flywheelSpeedMap.get(lookaheadShooterToTargetDistance),
        lookaheadShooterToTargetDistance,
        shooterToTargetDistance,
        timeOfFlight,
        passing);

    if (showData) {
      loopTST++;
      SmartDashboard.putNumber("LC/TST", loopTST);
    }
    if (latestParameters != null) {
      Pose2d derivedPose = new Pose2d(robotPose.getTranslation(), driveAngle);

      if (showData) {
        SmartDashboard.putBoolean("LC/LPValid", latestParameters.isValid);
        SmartDashboard.putNumber("LC/DriveAngle", latestParameters.driveAngle.getDegrees());
        SmartDashboard.putNumber("LC/RobotAngle", drivetrain.getState().Pose.getRotation().getDegrees());
        SmartDashboard.putNumber("LC/DriveVel", latestParameters.driveVelocity);
        SmartDashboard.putNumber("LC/HoodAngle", latestParameters.hoodAngle);
        SmartDashboard.putNumber("LC/HoodVel", latestParameters.hoodVelocity);
        SmartDashboard.putNumber("LC/ShtrSpeed", latestParameters.flywheelSpeed);
        SmartDashboard.putNumber("LC/DistNoLkAhd", latestParameters.distanceNoLookahead);
        SmartDashboard.putNumber("LC/TOF", latestParameters.timeOfFlight);
        SmartDashboard.putBoolean("LC/Passing", latestParameters.passing);
        SmartDashboard.putNumber("LC/DAWLO", getDriveAngleWithLauncherOffset(lookaheadRobotPose, target).getDegrees());

        stAimedPosePublisher.accept(getStationaryAimedPose(drivetrain.getState().Pose.getTranslation(), false));
        derivedPosePublisher.accept(derivedPose);
        drivetrain.projectedOnTheMoveShootPose = getProjectedHubPose(lookaheadRobotPose,
            lookaheadShooterToTargetDistance, driveAngle);

        projectedHubPosePublisher
            .accept(drivetrain.projectedOnTheMoveShootPose);

        SmartDashboard.putNumber("LC/projectedYDiff",
            drivetrain.projectedOnTheMoveShootPose.getY() - target.getY());
      }
    }
    // Log calculated values
    DogLog.log("LaunchCalculator/TargetPose", new Pose2d(target, Rotation2d.kZero));
    DogLog.log("LaunchCalculator/LookaheadPose", lookaheadPose);
    DogLog.log("LaunchCalculator/LauncherToTargetDistance", lookaheadShooterToTargetDistance);

    return latestParameters;
  }

  private static Rotation2d getDriveAngleWithLauncherOffset(
      Pose2d robotPose, Translation2d target) {
    Rotation2d fieldToHubAngle = target.minus(robotPose.getTranslation()).getAngle();
    Rotation2d hubAngle = new Rotation2d(
        Math.asin(
            MathUtil.clamp(
                LauncherConstants.robotToShooter.getTranslation().getY()
                    / target.getDistance(robotPose.getTranslation()),
                -1.0,
                1.0)));

    Rotation2d driveAngle = fieldToHubAngle.plus(hubAngle)
        .plus(LauncherConstants.robotToShooter.getRotation().toRotation2d());

    // SmartDashboard.putNumber("LC/tgtx", target.getX());
    // SmartDashboard.putNumber("LC/tgty", target.getY());
    // SmartDashboard.putNumber("LC/robx", robotPose.getX());
    // SmartDashboard.putNumber("LC/roby", robotPose.getY());
    // SmartDashboard.putNumber("LC/fieldToHubAngle", fieldToHubAngle.getDegrees());
    // SmartDashboard.putNumber("LC/HubAngle", hubAngle.getDegrees());

    return driveAngle;
  }

  public double getNaiveTOF(double distance) {
    return timeOfFlightMap.get(distance);
  }

  public void clearLaunchingParameters() {
    latestParameters = null;
  }

  public Translation2d getPassingTarget() {
    double flippedY = AllianceFlipUtil.applyX(drivetrain.getState().Pose.getTranslation().getMeasureX().in(Meters));
    boolean mirror = flippedY > FieldConstants.LinesHorizontal.center;

    // Check if we need to interpolate
    if (FieldConstants.fieldWidth - hubPassLine > flippedY && flippedY > hubPassLine) {
      double interpolateZoneAmount = ((mirror ? FieldConstants.fieldWidth - flippedY : flippedY) - hubPassLine)
          / (FieldConstants.LinesHorizontal.center - hubPassLine);
      var unflippedPoseY = mirror
          ? FieldConstants.fieldWidth
              - MathUtil.interpolate(yPassTarget, passingMinDistance, interpolateZoneAmount)
          : MathUtil.interpolate(yPassTarget, passingMinDistance, interpolateZoneAmount);
      Translation2d flippedGoalTranslation = AllianceFlipUtil.apply(new Translation2d(xPassTarget, unflippedPoseY));
      return flippedGoalTranslation;
    }

    // Fixed passing target
    Translation2d flippedGoalTranslation = AllianceFlipUtil.apply(
        new Translation2d(
            xPassTarget, mirror ? FieldConstants.fieldWidth - yPassTarget : yPassTarget));

    return flippedGoalTranslation;
  }

  /**
   * Returns the Pose2d that correctly aims the robot at the goal for a given
   * robot translation.
   *
   * @param robotTranslation The translation of the center of the robot.
   * @param forceBlue        Always use the blue hub target
   * @return The target pose for the aimed robot.
   */
  public static Pose2d getStationaryAimedPose(Translation2d robotTranslation, boolean forceBlue) {
    // Calculate target
    Translation2d target = FieldConstants.Hub.topCenterPoint.toTranslation2d();
    if (!forceBlue) {
      target = AllianceFlipUtil.apply(target);
    }
    return new Pose2d(
        robotTranslation, getDriveAngleWithLauncherOffset(new Pose2d(robotTranslation, new Rotation2d()), target));
  }

  /** Adjusts the hood angle offset up or down the specified amount. */
  public void incrementHoodAngleOffset(double incrementDegrees) {
    hoodAngleOffsetDeg += incrementDegrees;
  }

  public Pose2d getProjectedHubPose(Pose2d robotPose, double distanceToHub, Rotation2d driveAngle) {

    /**
     * calculate the pose where the computed drive angle hits the x center line of
     * the hub
     * Use the distance to the hub as the hypotenuse and break it into x and y
     * components
     * 
     */

    double xDistToHub = distanceToHub * driveAngle.getCos();
    double yDistToHub = distanceToHub * driveAngle.getSin();
    Pose2d temp = new Pose2d(robotPose.getX() + xDistToHub, robotPose.getY() + yDistToHub, driveAngle);

    return temp;

  }

}
