// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.utils;

import static edu.wpi.first.units.Units.Meters;

import dev.doglog.DogLog;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Constants;
import frc.robot.Constants.FieldConstants;
import frc.robot.Constants.LauncherConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;
import frc.robot.utils.geometry.AllianceFlipUtil;
import frc.robot.utils.geometry.GeomUtil;

/**
 * Read the estimated robot pose and shift it forward by a fixed (small) amount
 * using a Twist2d. We know that subsystems will not perfectly track the
 * setpoints, so this step helps to account for that phase delay by
 * calculating using a future robot position. We manually measure the phase
 * delay in subsystem tracking, and want to minimize it as much as possible to
 * improve the consistency under acceleration.
 * 
 * Calculate the position and velocity of the shooter. While we can
 * measure distance from anywhere on the robot with a fixed launcher, it’s very
 * important to measure from the shooter itself since we can launch in any
 * orientation. The same thing applies to velocity calculations, since the robot
 * and shooter velocities may be different (particularly when the robot is
 * turning).
 * 
 * Account for the velocity applied to the fuel by the robot (code). This is the
 * core of the algorithm, and involves three steps:
 * 
 * Calculate the expected time-of-flight of the ball using a lookup table
 * generated by sampling the time at several distances using a slo-mo video.
 * 
 * Shift the launcher position forward by the time-of-flight. We use a simple
 * transform and not a twist because we are not predicting the movement of the
 * robot; we are accounting for the offset of the ball over the course of its
 * flight.
 * 
 * Calculate the time-of-flight at the new lookahead position, and repeat the
 * calculation several times. This ensures that the time-of-flight used during
 * calculation matches the time-of-flight of the lookahead position.
 * 
 * Calculate the launch parameters using the lookahead position (code). This
 * step also calculates the derivative of the turret and hood setpoints, which
 * are fed to those subsystems to minimize phase delay during tracking.
 * 
 * 
 */
public class LaunchCalculator {

  private static LaunchCalculator instance;

  public static LaunchCalculator getInstance() {
    if (instance == null)
      instance = new LaunchCalculator();

    return instance;
  }

  public record LaunchingParameters(
      boolean isValid,
      Rotation2d driveAngle,
      double driveVelocity,
      double hoodAngle,
      double hoodVelocity,
      double flywheelSpeed,
      double distance,
      double distanceNoLookahead,
      double timeOfFlight,
      boolean passing) {
  }

  // Cache parameters
  private LaunchingParameters latestParameters = null;

  private static final double phaseDelay = .03;
  private final int loops = 20;

  private Rotation2d lastDriveAngle = new Rotation2d();

  private double lastHoodAngle;

  private double hoodAngleOffsetDeg = 0.0;

  public double getHoodAngleOffsetDeg() {
    return hoodAngleOffsetDeg;
  }

  private int loopTST;

  boolean showData = true;

  StructPublisher<Pose2d> robotPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/RobotPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> estimatedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/EstimatedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> lookAheadRobotPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LookAheadRobotPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> lookAheadPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LookAheadPose", Pose2d.struct).publish();

  StructPublisher<Pose2d> shooterPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/LauncherPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> stAimedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/StAimedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> derivedPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/DerivedPose", Pose2d.struct).publish();
  StructPublisher<Pose2d> projectedHubPosePublisher = NetworkTableInstance.getDefault()
      .getStructTopic("LC/ProjectedHubPose", Pose2d.struct).publish();

  public LaunchingParameters getParameters(CommandSwerveDrivetrain drivetrain) {
    boolean passing = AllianceFlipUtil
        .applyX(drivetrain.getState().Pose.getX()) > FieldConstants.LinesVertical.hubCenter;
    if (latestParameters != null) {
      return latestParameters;
    }

    /**
     * Read the estimated robot pose and shift it forward by a fixed (small) amount
     * using a Twist2d. We know that subsystems will not perfectly track the
     * setpoints, so this step helps to account for that phase delay by
     * calculating using a future robot position. We manually measure the phase
     * delay in subsystem tracking, and want to minimize it as much as possible to
     * improve the consistency under acceleration.
     */

    Pose2d robotPose = drivetrain.getState().Pose;
    ChassisSpeeds robotRelativeVelocity = drivetrain.getState().Speeds;
    Pose2d estimatedPose = robotPose.exp(
        new Twist2d(
            robotRelativeVelocity.vxMetersPerSecond * phaseDelay,
            robotRelativeVelocity.vyMetersPerSecond * phaseDelay,
            robotRelativeVelocity.omegaRadiansPerSecond * phaseDelay));

    if (showData) {
      robotPosePublisher.accept(robotPose);
      estimatedPosePublisher.accept(estimatedPose);
    }

    /**
     * Calculate the position and velocity of the shooter. While we can
     * measure distance from anywhere on the robot with a fixed launcher, it’s very
     * important to measure from the shooter itself since we can launch in any
     * orientation. The same thing applies to velocity calculations, since the robot
     * and shooter velocities may be different (particularly when the robot is
     * turning).
     */

    Translation2d target = passing
        ? getPassingTarget(drivetrain)
        : AllianceFlipUtil.apply(FieldConstants.Hub.topCenterPoint.toTranslation2d());

    Pose2d shooterPose = estimatedPose.transformBy(LauncherConstants.toTransform2d(LauncherConstants.robotToShooter));

    double shooterToTargetDistance = target.getDistance(shooterPose.getTranslation());

    if (showData) {
      shooterPosePublisher.accept(shooterPose);
      SmartDashboard.putNumber("LC/Lchr2TgtDist", shooterToTargetDistance);
    }
    /**
     * 
     * Account for the velocity applied to the fuel by the robot. This is the
     * core of the algorithm, and involves three steps:
     * 
     * Calculate the expected time-of-flight of the ball using a lookup table
     * generated by sampling the time at several distances using a slo-mo video.
     * 
     * Shift the launcher position forward by the time-of-flight. We use a simple
     * transform and not a twist because we are not predicting the movement of the
     * robot; we are accounting for the offset of the ball over the course of its
     * flight.
     * 
     * Calculate the time-of-flight at the new lookahead position, and repeat the
     * calculation several times. This ensures that the time-of-flight used during
     * calculation matches the time-of-flight of the lookahead position.
     * 
     */

    ChassisSpeeds shootererVelocity = GeomUtil.transformVelocity(
        drivetrain.getState().Speeds,
        LauncherConstants.robotToShooter.getTranslation().toTranslation2d(),
        drivetrain.getState().Pose.getRotation());

    // Account for imparted velocity by robot (shooter) to offset
    double timeOfFlight = passing
        ? ShootingData.passingTimeOfFlightMap.get(shooterToTargetDistance)
        : ShootingData.timeOfFlightMap.get(shooterToTargetDistance);
    Pose2d lookaheadPose = shooterPose;
    double lookaheadShooterToTargetDistance = shooterToTargetDistance;

    // loop to get better time of filght
    for (int i = 0; i < loops; i++) {
      timeOfFlight = passing
          ? ShootingData.passingTimeOfFlightMap.get(lookaheadShooterToTargetDistance)
          : ShootingData.timeOfFlightMap.get(lookaheadShooterToTargetDistance);
      double offsetX = shootererVelocity.vxMetersPerSecond * timeOfFlight;
      double offsetY = shootererVelocity.vyMetersPerSecond * timeOfFlight;
      lookaheadPose = new Pose2d(
          shooterPose.getTranslation().plus(new Translation2d(offsetX, offsetY)),
          shooterPose.getRotation());
      lookaheadShooterToTargetDistance = target.getDistance(lookaheadPose.getTranslation());

      if (showData) {
        lookAheadPosePublisher.accept(lookaheadPose);
      }
    }

    // Account for shoother being off center
    Pose2d lookaheadRobotPose = lookaheadPose
        .transformBy(LauncherConstants.toTransform2d(LauncherConstants.robotToShooter).inverse());
    Rotation2d driveAngle = getDriveAngleWithLauncherOffset(lookaheadRobotPose, target);

    LinearFilter hoodAngleFilter = LinearFilter.movingAverage((int) (0.4 / Constants.loopPeriodSecs));
    LinearFilter driveAngleFilter = LinearFilter.movingAverage((int) (1.5 / Constants.loopPeriodSecs));

    if (showData) {
      lookAheadRobotPosePublisher.accept(lookaheadRobotPose);
    }
    /**
     * 
     * Calculate the launch parameters using the lookahead position (code). This
     * step also calculates the derivative of the turret and hood setpoints, which
     * are fed to those subsystems to minimize phase delay during tracking.
     * 
     */
    double hoodAngle = passing
        ? ShootingData.passingHoodAngleMap.get(lookaheadShooterToTargetDistance).getRadians()
        : ShootingData.hoodAngleMap.get(lookaheadShooterToTargetDistance).getRadians();

    if (lastDriveAngle == null)
      lastDriveAngle = driveAngle;

    if (Double.isNaN(lastHoodAngle))
      lastHoodAngle = hoodAngle;

    double hoodVelocity = hoodAngleFilter.calculate((hoodAngle - lastHoodAngle) / Constants.loopPeriodSecs);
    lastHoodAngle = hoodAngle;

    double driveVelocity = driveAngleFilter.calculate(
        driveAngle.minus(lastDriveAngle).getRadians() / Constants.loopPeriodSecs);

    lastDriveAngle = driveAngle;

    if (showData) {
      SmartDashboard.putNumber("LC/LchrVelX", shootererVelocity.vxMetersPerSecond);
      SmartDashboard.putNumber("LC/LchrVelY", shootererVelocity.vyMetersPerSecond);
      SmartDashboard.putNumber("LC/LkAhdLchr2TgtDis", lookaheadShooterToTargetDistance);
    }

    // Construct parameters
    latestParameters = new LaunchingParameters(
        lookaheadShooterToTargetDistance >= (passing ? ShootingData.passingMinDistance : ShootingData.minDistance)
            && lookaheadShooterToTargetDistance <= (passing ? ShootingData.passingMaxDistance
                : ShootingData.maxDistance),
        driveAngle,
        driveVelocity,
        hoodAngle + Units.degreesToRadians(hoodAngleOffsetDeg),
        hoodVelocity,
        passing
            ? ShootingData.passingShooterSpeedMap.get(lookaheadShooterToTargetDistance)
            : ShootingData.shooterSpeedMap.get(lookaheadShooterToTargetDistance),
        lookaheadShooterToTargetDistance,
        shooterToTargetDistance,
        timeOfFlight,
        passing);

    if (showData) {
      loopTST++;
      SmartDashboard.putNumber("LC/TST", loopTST);
    }
    if (latestParameters != null) {
      Pose2d derivedPose = new Pose2d(robotPose.getTranslation(), driveAngle);

      Pose2d projectedOnTheMoveShootPose = getProjectedHubPose((drivetrain.getState().Pose),
          lookaheadShooterToTargetDistance, driveAngle);

      Rotation2d projectedOnTheMoveShootAngle = latestParameters.driveAngle;

      if (showData) {
        SmartDashboard.putBoolean("LC/LPValid", latestParameters.isValid);
        SmartDashboard.putNumber("LC/DriveAngle", latestParameters.driveAngle.getDegrees());
        SmartDashboard.putNumber("LC/RobotAngle", drivetrain.getState().Pose.getRotation().getDegrees());
        SmartDashboard.putNumber("LC/DriveVel", latestParameters.driveVelocity);
        SmartDashboard.putNumber("LC/HoodAngle", latestParameters.hoodAngle);
        SmartDashboard.putNumber("LC/HoodVel", latestParameters.hoodVelocity);
        SmartDashboard.putNumber("LC/ShtrSpeed", latestParameters.flywheelSpeed);
        SmartDashboard.putNumber("LC/DistNoLkAhd", latestParameters.distanceNoLookahead);
        SmartDashboard.putNumber("LC/TOF", latestParameters.timeOfFlight);
        SmartDashboard.putBoolean("LC/Passing", latestParameters.passing);
        SmartDashboard.putNumber("LC/DAWLO", getDriveAngleWithLauncherOffset(lookaheadRobotPose, target).getDegrees());

        stAimedPosePublisher.accept(getStationaryAimedPose(drivetrain.getState().Pose.getTranslation(), false));
        derivedPosePublisher.accept(derivedPose);

        projectedHubPosePublisher
            .accept(drivetrain.projectedOnTheMoveShootPose);

        SmartDashboard.putNumber("LC/DriveAngle", driveAngle.getDegrees());
        SmartDashboard.putNumber("LC/projectedYDiff",
            drivetrain.projectedOnTheMoveShootPose.getY() - target.getY());

      }
    }
    // Log calculated values
    DogLog.log("LaunchCalculator/TargetPose", new Pose2d(target, Rotation2d.kZero));
    DogLog.log("LaunchCalculator/LookaheadPose", lookaheadPose);
    DogLog.log("LaunchCalculator/LauncherToTargetDistance", lookaheadShooterToTargetDistance);

    return latestParameters;
  }

  private static Rotation2d getDriveAngleWithLauncherOffset(
      Pose2d robotPose, Translation2d target) {
    Rotation2d fieldToHubAngle = target.minus(robotPose.getTranslation()).getAngle();
    Rotation2d hubAngle = new Rotation2d(
        Math.asin(
            MathUtil.clamp(
                LauncherConstants.robotToShooter.getTranslation().getY()
                    / target.getDistance(robotPose.getTranslation()),
                -1.0,
                1.0)));

    Rotation2d driveAngle = fieldToHubAngle.plus(hubAngle)
        .plus(LauncherConstants.robotToShooter.getRotation().toRotation2d());

    // SmartDashboard.putNumber("LC/tgtx", target.getX());
    // SmartDashboard.putNumber("LC/tgty", target.getY());
    // SmartDashboard.putNumber("LC/robx", robotPose.getX());
    // SmartDashboard.putNumber("LC/roby", robotPose.getY());
    // SmartDashboard.putNumber("LC/fieldToHubAngle", fieldToHubAngle.getDegrees());
    // SmartDashboard.putNumber("LC/HubAngle", hubAngle.getDegrees());

    return driveAngle;
  }

  public double getNaiveTOF(double distance) {
    return ShootingData.timeOfFlightMap.get(distance);
  }

  public void clearLaunchingParameters() {
    latestParameters = null;
  }

  public Translation2d getPassingTarget(CommandSwerveDrivetrain drivetrain) {
    double flippedY = AllianceFlipUtil.applyX(drivetrain.getState().Pose.getTranslation().getMeasureX().in(Meters));
    boolean mirror = flippedY > FieldConstants.LinesHorizontal.center;

    // Check if we need to interpolate
    if (FieldConstants.fieldWidth - ShootingData.hubPassLine > flippedY && flippedY > ShootingData.hubPassLine) {
      double interpolateZoneAmount = ((mirror ? FieldConstants.fieldWidth - flippedY : flippedY)
          - ShootingData.hubPassLine)
          / (FieldConstants.LinesHorizontal.center - ShootingData.hubPassLine);
      var unflippedPoseY = mirror
          ? FieldConstants.fieldWidth
              - MathUtil.interpolate(ShootingData.yPassTarget, ShootingData.passingMinDistance, interpolateZoneAmount)
          : MathUtil.interpolate(ShootingData.yPassTarget, ShootingData.passingMinDistance, interpolateZoneAmount);
      Translation2d flippedGoalTranslation = AllianceFlipUtil
          .apply(new Translation2d(ShootingData.xPassTarget, unflippedPoseY));
      return flippedGoalTranslation;
    }

    // Fixed passing target
    Translation2d flippedGoalTranslation = AllianceFlipUtil.apply(
        new Translation2d(
            ShootingData.xPassTarget,
            mirror ? FieldConstants.fieldWidth - ShootingData.yPassTarget : ShootingData.yPassTarget));

    return flippedGoalTranslation;
  }

  /**
   * Returns the Pose2d that correctly aims the robot at the goal for a given
   * robot translation.
   *
   * @param robotTranslation The translation of the center of the robot.
   * @param forceBlue        Always use the blue hub target
   * @return The target pose for the aimed robot.
   */
  public static Pose2d getStationaryAimedPose(Translation2d robotTranslation, boolean forceBlue) {
    // Calculate target
    Translation2d target = FieldConstants.Hub.topCenterPoint.toTranslation2d();
    if (!forceBlue) {
      target = AllianceFlipUtil.apply(target);
    }
    return new Pose2d(
        robotTranslation, getDriveAngleWithLauncherOffset(new Pose2d(robotTranslation, new Rotation2d()), target));
  }

  /** Adjusts the hood angle offset up or down the specified amount. */
  public void incrementHoodAngleOffset(double incrementDegrees) {
    hoodAngleOffsetDeg += incrementDegrees;
  }

  public Pose2d getProjectedHubPose(Pose2d robotPose, double distanceToHub, Rotation2d driveAngle) {

    /**
     * calculate the pose where the computed drive angle hits the x center line of
     * the hub
     * Use the distance to the hub as the hypotenuse and break it into x and y
     * components
     * 
     */

    double xDistToHub = distanceToHub * driveAngle.getCos();
    double yDistToHub = distanceToHub * driveAngle.getSin();
    Pose2d temp = new Pose2d(robotPose.getX() + xDistToHub, robotPose.getY() + yDistToHub, driveAngle);

    return temp;

  }

}
